



DROP DATABASE IF EXISTS colegio;

CREATE DATABASE colegio;

USE colegio;


DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS matricula;
DROP TABLE IF EXISTS pago;
DROP TABLE IF EXISTS administrador;
DROP TABLE IF EXISTS grado;
DROP TABLE IF EXISTS seccion;
DROP TABLE IF EXISTS nivel;
DROP TABLE IF EXISTS estudiante;
DROP TABLE IF EXISTS Contador;

CREATE TABLE Contador (
	vch_conttabla        VARCHAR(30) NOT NULL,
	int_contitem         INTEGER NOT NULL,
	int_contlongitud     INTEGER NOT NULL,
	CONSTRAINT PK_Contador 
		PRIMARY KEY (vch_conttabla)
) ENGINE = INNODB ;

CREATE TABLE NIVEL(
nivel int not null,
nombreNivel  varchar(30) not null,
CONSTRAINT PK_NIVEL PRIMARY KEY(NIVEL)

) ENGINE = INNODB ;


CREATE TABLE Usuario(
usuario INT NOT NULL,
nombreUsuario varchar(15)not null,
claveUsuario varchar(15) not null,
CONSTRAINT PK_USUARIO PRIMARY KEY(USUARIO)



) ENGINE = INNODB ;




CREATE TABLE MATRICULA(
MATRICULA INT NOT NULL,
PAGO DECIMAL(12,3) NOT NULL,
FECHA DATE NOT NULL,

CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA)



) ENGINE = INNODB ;





CREATE TABLE PAGO(
PAGO INT NOT NULL,
MONTO DECIMAL(12,3) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL,

CONSTRAINT PK_PAGO PRIMARY KEY (PAGO)


) ENGINE = INNODB ;





CREATE TABLE ADMINISTRADOR(
ADMINISTRADOR INT NOT NULL,
NOMBREADMIN VARCHAR(14) NOT NULL,
CLAVEADMIN VARCHAR(14) NOT NULL,


CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (ADMINISTRADOR)



) ENGINE = INNODB ;




CREATE TABLE GRADO(
GRADO INT NOT NULL,
GRADONOMBRE VARCHAR(10) NOT NULL,

CONSTRAINT PK_GRADO PRIMARY KEY (GRADO)
) ENGINE = INNODB ;





CREATE TABLE SECCION(
SECCION INT NOT NULL,
GRADONOMBRE VARCHAR(10) NOT NULL,

CONSTRAINT PK_SECCION PRIMARY KEY(SECCION)
) ENGINE = INNODB ;







CREATE TABLE ESTUDIANTE(
ESTUDIANTE INT NOT NULL,
NOMBREESTUDIANTE VARCHAR(20) NOT NULL,
APELLIDOSESTUDIANTE VARCHAR(20) NOT NULL,
FECHANACIMESTUDIANTE date NOT NULL,
DISTRITOESTUDIANTE  VARCHAR(20)NOT NULL,
CIUDADESTUDIANTE VARCHAR(20) NOT NULL,
TELEFONOESTUDIANTE INT NOT NULL,
USUARIO INT null,
MATRICULA INT  NULL,
PAGO INT  NULL,
GRADO INT  NULL,
NIVEL int  null,
CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (ESTUDIANTE),
KEY idx_estudiante01 (usuario),
	CONSTRAINT fk_estudiante_usuario
		FOREIGN KEY (usuario)
		REFERENCES usuario (usuario)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT, 
	KEY idx_estudiante02 (matricula),
	CONSTRAINT fk_estudiante_matricula
		FOREIGN KEY (matricula)
		REFERENCES matricula (matricula)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT,
		KEY idx_estudiante03 (pago),
	CONSTRAINT fk_estudiante_pago
		FOREIGN KEY (pago)
		REFERENCES pago (pago)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT,
		KEY idx_estudiante04 (grado),
	CONSTRAINT fk_estudiante_grado
		FOREIGN KEY (grado)
		REFERENCES grado (grado)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT,
		KEY idx_estudiante05 (nivel),
	CONSTRAINT fk_estudiante_nivel
		FOREIGN KEY (nivel)
		REFERENCES nivel (nivel)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT



) ENGINE = INNODB;


USE MYSQL;
GRANT ALL PRIVILEGES ON *.* TO 'almasSaber'@'%' IDENTIFIED BY 'colegio' WITH GRANT OPTION;
FLUSH PRIVILEGES;
USE colegio;

USE MYSQL;
GRANT ALL PRIVILEGES ON *.* TO 'almasSaber'@'localhost' IDENTIFIED BY 'colegio' WITH GRANT OPTION;
FLUSH PRIVILEGES;
USE colegio;



